import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const interfont = Inter({
  weight: "500",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interfont.className}`}>{children}</body>
    </html>
  );
}
